**RISK Analysis**

This project is for examining the probability of success if an attacking force of ```a``` attackers attacks ```b``` defenders. 

In [1]:
from numpy import zeros, set_printoptions
set_printoptions(suppress=True, precision=4, linewidth=300)

dim = 15
table = zeros((dim,dim))
for i in range(2,dim): table[i][0] = 1
for j in range(1, dim): table[2][j] = (15/36)*(55/216)**(j-1)
for i in range(3,dim): table[i][1] = 1-(21/36)*(91/216)*(441/1296)**(i-3)

last=table[3][0]
for j in range(2,dim,2): 
    last = (295/1296)*last + (15/36)*(420/1296)*(55/216)**(j-2)
    table[3][j] = last

last=table[3][1]
for j in range(3,dim,2): 
    last = (295/1296)*last + (15/36)*(420/1296)*(55/216)**(j-2)
    table[3][j] = last

for i in range(4,dim):
    for j in range(2,dim):
        table[i][j] = (2890/7776)*table[i][j-2] + (2611/7776)*table[i-1][j-1] +(2275/7776)*table[i-2][j]

print(table)

[[0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.    ]
 [0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.    ]
 [1.     0.4167 0.1061 0.027  0.0069 0.0018 0.0004 0.0001 0.     0.     0.     0.     0.     0.     0.    ]
 [1.     0.7542 0.3627 0.2061 0.0913 0.0491 0.0214 0.0113 0.0049 0.0026 0.0011 0.0006 0.0003 0.0001 0.0001]
 [1.     0.9164 0.656  0.4703 0.315  0.2059 0.1337 0.0837 0.0535 0.0328 0.0208 0.0126 0.0079 0.0048 0.003 ]
 [1.     0.9715 0.7855 0.6416 0.4765 0.3586 0.2525 0.1815 0.1234 0.0862 0.0572 0.0392 0.0255 0.0173 0.0111]
 [1.     0.9903 0.8898 0.7694 0.6383 0.5062 0.3968 0.2974 0.224  0.1616 0.1183 0.0829 0.0594 0.0408 0.0288]
 [1.     0.9967 0.934  0.8569 0.7449 0.6377 0.5207 0.4233 0.3295 0.2578 0.1934 0.147  0.1072 0.0796 0.0568]
 [1.     0.9989 0.9666 0.9099 0.8337 0.7364 0.6401 0.5355 0.4456 0.3569 0.2868 0.2219 0.1733 0.1304 0.0996]
 [1.     0.9996 0.9803 0.946

In [2]:
# 2 dimensional
prec = 50 #relates to dim
R.<x,y> = PowerSeriesRing(QQ, default_prec=prec); R

def T_1(x,y): return y*(5 * (49*(x**4) + 203*(x**3) + 432*(x**2))) / (36 * (49*(x**2) - 193*x + 144))

def T_2(x,y): return (x**2)*(216 + (35*y))/(216 - (55*y))

def T_3(x,y): return (x**3)*(559872 + 279720*y - 31925*(y**2))/(2*(16225*(y**3) - 63720*(y**2) - 71280*y + 279936))

f = ( ((x**2)/(1-x)) + T_1(x,y) + T_2(x,y) + T_3(x,y) - (x**2) - (x**3) - (15/36)*(x**2)*y - (1955/2592)*(x**3)*y \
     - (2890/7776)*(y**2)*(T_2(x,y) + T_3(x,y)) \
        - (2611/7776)*x*y*(((x**2)/(1-x)) + T_2(x,y) - x**2 ) \
            - (2275/7776)*(x**2)*(((x**2)/(1-x)) + T_1(x,y))) \
                / (1-(2890/7776)*(y**2) - (2611/7776)*x*y - (2275/7776)*(x**2))


f = -1/36*(1074213000*(49*x^4 - 193*x^3 + 144*x^2)*y^5 + 1123411161600*x^5 - 25*(361736375*x^6 + 66673957*x^5 - 4680693108*x^4 + 36023206464*x^3 - 38185509888*x^2)*y^4 - 3301453209600*x^4 + 1260*(28187250*x^6 - 50848105*x^5 + 447624072*x^4 + 187126848*x^3 - 869667840*x^2)*y^3 - 3839844040704*x^3 + 6480*(6131125*x^6 - 102300583*x^5 + 288594180*x^4 + 557456256*x^3 - 1043601408*x^2)*y^2 + 11284439629824*x^2 - 326592*(477750*x^6 + 2855125*x^5 - 3942792*x^4 + 1842912*x^3 - 5598720*x^2)*y)/(46890250*(49*x^2 - 193*x + 144)*y^5 + 1475*(1407329*x^3 - 11660705*x^2 + 28231488*x - 17978112)*y^4 + 31205865600*x^4 + 5*(361736375*x^4 - 3055252991*x^3 + 4229841672*x^2 + 8030021184*x - 9566346240)*y^3 - 122912899200*x^3 - 1080*(6577025*x^4 - 17461451*x^3 - 73116246*x^2 + 257934240*x - 173933568)*y^2 - 14955300864*x^2 - 1296*(6131125*x^4 - 51783949*x^3 + 105909048*x^2 + 1329696*x - 61585920)*y + 420118990848*x - 313456656384)


from numpy import zeros, set_printoptions
set_printoptions(suppress=True, precision=4, linewidth=300)


gftable=zeros((dim,dim))
coefs = f.coefficients()

for n in range(1,dim):
    for m in range(dim):
        try:
            gftable[n][m] = coefs[x^n*y^m]
        except KeyError:
            pass

print(gftable)

[[0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.    ]
 [0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.    ]
 [1.     0.4167 0.1061 0.027  0.0069 0.0018 0.0004 0.0001 0.     0.     0.     0.     0.     0.     0.    ]
 [1.     0.7542 0.3627 0.2061 0.0913 0.0491 0.0214 0.0113 0.0049 0.0026 0.0011 0.0006 0.0003 0.0001 0.0001]
 [1.     0.9164 0.656  0.4703 0.315  0.2059 0.1337 0.0837 0.0535 0.0328 0.0208 0.0126 0.0079 0.0048 0.003 ]
 [1.     0.9715 0.7855 0.6416 0.4765 0.3586 0.2525 0.1815 0.1234 0.0862 0.0572 0.0392 0.0255 0.0173 0.0111]
 [1.     0.9903 0.8898 0.7694 0.6383 0.5062 0.3968 0.2974 0.224  0.1616 0.1183 0.0829 0.0594 0.0408 0.0288]
 [1.     0.9967 0.934  0.8569 0.7449 0.6377 0.5207 0.4233 0.3295 0.2578 0.1934 0.147  0.1072 0.0796 0.0568]
 [1.     0.9989 0.9666 0.9099 0.8337 0.7364 0.6401 0.5355 0.4456 0.3569 0.2868 0.2219 0.1733 0.1304 0.0996]
 [1.     0.9996 0.9803 0.946

In [53]:
# 2 dimensional
prec = 50 #relates to dim
R.<x,y> = PowerSeriesRing(QQ, default_prec=prec); R

# 7776 + 7776*x + 3240*y + 3254*x*y
T_1 = -(x**2)*(7776+7776*x+3240*y+3254*x*y)/(7776-2275*(x**2)-2611*x*y-2890*(y**2))

# 7776 - 2275*x^2 - 2611*x*y
T_2 = (x**2)*(7776-2611*x*y-2275*(x**2))/((1-x)*(7776-2275*(x**2)-2611*x*y-2890*(y**2)))

# 7776 + 1260*y - 2611*x*y - 2890*y^2 - 91385/216*x*y^2 - 50575/108*y^3
T_3 = (x**2)*(7776+1260*y-2611*x*y - 2890*(y**2) - (91385/216)*x*(y**2) - (50575/108)*(y**3))/((1-(55/216)*y)*(7776-2275*(x**2)-2611*x*y-2890*(y**2)))

# -3240*y - 3045/2*x*y + 6965/12*x^2*y + 2309125/5184*x^3*y + 557375/5184*x^4*y
T_4 = (x**2)*(3240*y+(3045/2)*x*y-(6965/12)*(x**2)*y - (2309125/5184)*(x**3)*y - (557375/5184)*(x**4)*y)/((1-x)*(1-(49/144)*x)*(7776-2275*(x**2)-2611*x*y-2890*(y**2)))

# -7776*x - 3885*x*y + 240005/72*x*y^2 + 1871275/1296*x*y^3 - 46131625/279936*x*y^4
T_5 = (x**2)*(7776*x + 3885*x*y - (240005/72)*x*(y**2) - (1871275/1296)*x*(y**3) + (46131625/279936)*x*(y**4))/((1-(55/216)*y)*(1-(295/1296)*(y**2))*(7776-2275*(x**2)-2611*x*y-2890*(y**2)))

# f= T_4
f = T_1 + T_2 + T_3 + T_4 + T_5

from numpy import zeros, set_printoptions
set_printoptions(suppress=True, precision=4, linewidth=300)


gftablesplit=zeros((dim,dim))
coefs = f.coefficients()

for n in range(1,dim):
    for m in range(dim):
        try:
            gftablesplit[n][m] = coefs[x^n*y^m]
        except KeyError:
            pass

print(gftablesplit)

[[0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.    ]
 [0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.    ]
 [1.     0.4167 0.1061 0.027  0.0069 0.0018 0.0004 0.0001 0.     0.     0.     0.     0.     0.     0.    ]
 [1.     0.7542 0.3627 0.2061 0.0913 0.0491 0.0214 0.0113 0.0049 0.0026 0.0011 0.0006 0.0003 0.0001 0.0001]
 [1.     0.9164 0.656  0.4703 0.315  0.2059 0.1337 0.0837 0.0535 0.0328 0.0208 0.0126 0.0079 0.0048 0.003 ]
 [1.     0.9715 0.7855 0.6416 0.4765 0.3586 0.2525 0.1815 0.1234 0.0862 0.0572 0.0392 0.0255 0.0173 0.0111]
 [1.     0.9903 0.8898 0.7694 0.6383 0.5062 0.3968 0.2974 0.224  0.1616 0.1183 0.0829 0.0594 0.0408 0.0288]
 [1.     0.9967 0.934  0.8569 0.7449 0.6377 0.5207 0.4233 0.3295 0.2578 0.1934 0.147  0.1072 0.0796 0.0568]
 [1.     0.9989 0.9666 0.9099 0.8337 0.7364 0.6401 0.5355 0.4456 0.3569 0.2868 0.2219 0.1733 0.1304 0.0996]
 [1.     0.9996 0.9803 0.946

In [55]:
from math import isclose

for i in range(dim):
    for j in range(dim):
        if not isclose(table[i][j], gftablesplit[i][j]):
            print(f"it is not close at {i,j}, with the true value of : {table[i][j]} differing from: {gftablesplit[i][j]}")

In [72]:
# define exact RISK 
from numpy import zeros, set_printoptions

def t_1(a,b):
    sum=0
    if (a+b)%2 == 1 or a<0 or b<0: return 0
    for j in range(((a+b)/2)+1): sum += binomial(((a+b)/2),((a-b)/2)+(2*j))*binomial(((a-b)/2)+(2*j), j) * ((2611/(85*sqrt(910)))**(b-(2*j)))
    return sum * ((2275/7776)**(a/2)) * ((2890/7776)**(b/2)) / 7776

def t_2(a,b): 
    sum = 0
    for i in range(a+1): 
        sum += t_1(i,b)
    return sum

def t_3(a,b): 
    sum = 0
    for j in range(b+1): 
        sum += t_1(a,j)*((55/216)**(b-j))
    return sum

def t_4(a,b): 
    sum = 0
    for i_2 in range(a+1): 
        for i_1 in range(i_2+1):
            sum += t_1(i_1,b)*((49/144)**(i_2-i_1))
    return sum

def t_5(a,b): 
    sum = 0
    for i_2 in range(b+1):
        for i_1 in range(i_2+1):
            sum += t_1(a,i_1)*(((55/216)**(b-i_2))*(((sqrt(295/1296))**(i_2-i_1)) + ((-sqrt(295/1296))**(i_2-i_1))))
    return sum/2

def t(a,b): 
    val = -7776*t_1(a-2,b) - 7776*t_1(a-3,b) - 3240*t_1(a-2,b-1) - 3254*t_1(a-3,b-1) + \
        7776*t_2(a-2,b) - 2611*t_2(a-3,b-1) - 2275*t_2(a-4,b) + \
        7776*t_3(a-2,b) + 1260*t_3(a-2,b-1) - 2611*t_3(a-3,b-1) - 2890*t_3(a-2,b-2) -\
        (91385/216)*t_3(a-3,b-2) - (50575/108)*t_3(a-2,b-3) + \
        3240 * t_4(a-2,b-1) + (3045/2)*t_4(a-3,b-1) - (6965/12)*t_4(a-4,b-1) - \
        (2309125/5184) * t_4(a-5,b-1) - (557375/5184) * t_4(a-6,b-1) + \
        7776*t_5(a-3,b) + 3885*t_5(a-3,b-1) - (240005/72)*t_5(a-3,b-2) -\
        (1871275/1296)*t_5(a-3,b-3) + (46131625/279936)*t_5(a-3,b-4)
    return val

set_printoptions(suppress=True, precision=4, linewidth=300)
the_table = zeros((dim,dim))
for i in range(2,dim):
    for j in range(dim):
        the_table[i][j] = t(i,j)
print(the_table)


[[0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.    ]
 [0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.     0.    ]
 [1.     0.4167 0.1061 0.027  0.0069 0.0018 0.0004 0.0001 0.     0.     0.     0.     0.     0.     0.    ]
 [1.     0.7542 0.3627 0.2061 0.0913 0.0491 0.0214 0.0113 0.0049 0.0026 0.0011 0.0006 0.0003 0.0001 0.0001]
 [1.     0.9164 0.656  0.4703 0.315  0.2059 0.1337 0.0837 0.0535 0.0328 0.0208 0.0126 0.0079 0.0048 0.003 ]
 [1.     0.9715 0.7855 0.6416 0.4765 0.3586 0.2525 0.1815 0.1234 0.0862 0.0572 0.0392 0.0255 0.0173 0.0111]
 [1.     0.9903 0.8898 0.7694 0.6383 0.5062 0.3968 0.2974 0.224  0.1616 0.1183 0.0829 0.0594 0.0408 0.0288]
 [1.     0.9967 0.934  0.8569 0.7449 0.6377 0.5207 0.4233 0.3295 0.2578 0.1934 0.147  0.1072 0.0796 0.0568]
 [1.     0.9989 0.9666 0.9099 0.8337 0.7364 0.6401 0.5355 0.4456 0.3569 0.2868 0.2219 0.1733 0.1304 0.0996]
 [1.     0.9996 0.9803 0.946

In [73]:
from math import isclose

for i in range(dim):
    for j in range(dim):
        if not isclose(gftablesplit[i][j], the_table[i][j]):
            print(f"it is not close at {i,j}, with the true value of : {gftablesplit[i][j]-the_table[i][j]}")

In [2]:
from random import random

# simulates RISK combat for a troops attacks b troops. Optional threshold to stop the attack if attacking force dips below a certain level
def combat_sim(a,b,threshold=0):
    x = random()
    if a==1 or b==0 or a<=threshold: return f"The combat ended with {a} attackers and {b} defenders."
    elif a==2 and b==1: 
        if x < (15/36): return combat_sim(a,b-1)
        else: return combat_sim(a-1,b)
    elif a==2 and b>=2: 
        if x < (53/216): return combat_sim(a,b-1)
        else: return combat_sim(a-1,b)
    elif a==3 and b==1: 
        if x < (125/216): return combat_sim(a,b-1)
        else: return combat_sim(a-1,b)
    elif a==3 and b>=2: 
        if x < (295/1296): return combat_sim(a,b-2)
        elif x < (715/1296): return combat_sim(a-1,b-1)
        else: return combat_sim(a-2,b)
    elif a>=4 and b==1: 
        if x < (855/1296): return combat_sim(a-1,b)
        else: return combat_sim(a,b-1)
    elif a>=4 and b>=2: 
        if x < (2890/7776): return combat_sim(a,b-2)
        elif x < (5501/7776): return combat_sim(a-1,b-1)
        else: return combat_sim(a-2,b)

print(combat_sim(30,30, threshold=10))

The combat ended with 7 attackers and 0 defenders.
